#!/usr/bin/env python3
"""
Sync glossaries from Google Sheets to local CSV files.
Uses Google Sheets API v4 with OAuth token from google-sheets-token.json.
Run daily via cron or manually.

Writes two files per locale. The CSV is the source of truth the pipeline loads at runtime
(glossaries/{locale}.csv). The Markdown twin is a human/agent-readable rendering of the same
data — it used to be generated by hand, so it silently drifted from the CSV; it is now written
on every sync so the two cannot diverge. Markdown generation is best-effort and never fails a
locale whose CSV synced successfully.
"""
import json, os, sys, csv, time, urllib.request, urllib.parse

GLOSSARIES = {
    'de-DE': '1FUEDcQh3PAaL2fHOufqjCfb1Y1pHNQTbtJYMK5J1Cp4',
    'pt-BR': '1FCt-Vy2fxQwTVCccAtHbE4PdksJ_qpdG-AsbN6Gcirg',
    'fr-FR': '1zf8uHkhof7m-x_7f5uSA8mG44N04xE5ytwRbgFQccF8',
    'es-MX': '124N3_9D4oyeO6sm3sLJtMMhS51NhDVJETKdEvoq6ruM',
    'ja-JP': '1hAG0TsviTpKop9w50whPKYi8ydO0RWNu5dVC468zQr4',
}

OUTDIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'glossaries')
SECRETS_DIR = os.path.expanduser('~/.openclaw/workspace/.secrets')
TOKEN_PATH = os.path.join(SECRETS_DIR, 'google-sheets-token.json')
CREDS_PATH = os.path.join(SECRETS_DIR, 'google-sheets-oauth-credentials.json')

def get_access_token():
    """Get a fresh access token, refreshing if needed."""
    with open(TOKEN_PATH) as f:
        token_data = json.load(f)
    with open(CREDS_PATH) as f:
        creds = json.load(f)['installed']
    
    # Always refresh to ensure token is valid
    data = urllib.parse.urlencode({
        'client_id': creds['client_id'],
        'client_secret': creds['client_secret'],
        'refresh_token': token_data['refresh_token'],
        'grant_type': 'refresh_token'
    }).encode()
    
    req = urllib.request.Request('https://oauth2.googleapis.com/token', data=data)
    resp = json.loads(urllib.request.urlopen(req).read())
    
    if 'access_token' not in resp:
        raise RuntimeError(f"Token refresh failed: {resp}")
    
    # Save refreshed token
    token_data['access_token'] = resp['access_token']
    with open(TOKEN_PATH, 'w') as f:
        json.dump(token_data, f, indent=2)
    
    return resp['access_token']

def fetch_sheet(access_token, sheet_id):
    """Fetch all values from a Google Sheet via Sheets API v4."""
    url = f"https://sheets.googleapis.com/v4/spreadsheets/{sheet_id}/values/Sheet1?majorDimension=ROWS"
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"Bearer {access_token}")
    
    resp = json.loads(urllib.request.urlopen(req).read())
    return resp.get('values', [])

# Sheet columns: 0 = English term, 1 = English notes, 2 = target term, 4 = target-language notes.
# Notes prefer the target language and fall back to English, since many rows only fill one side.
COL_EN, COL_NOTES_EN, COL_TARGET, COL_NOTES_TARGET = 0, 1, 2, 4
NOTES_MAX = 100  # keep table rows readable; the CSV keeps the untruncated note


def _cell(row, idx):
    """Table-safe cell: collapse newlines, escape pipes, drop padding."""
    val = row[idx] if len(row) > idx else ''
    return val.replace('\r', ' ').replace('\n', ' ').replace('|', '\\|').strip()


def write_markdown(locale, rows):
    """Render the sheet as a Markdown table alongside the CSV. Mirrors the previous
    hand-written format so the switch to generation produces no spurious diff."""
    entries = []
    for row in rows[1:]:
        en, target = _cell(row, COL_EN), _cell(row, COL_TARGET)
        if not en or not target:
            continue  # a row without both sides is not a glossary entry
        notes = _cell(row, COL_NOTES_TARGET) or _cell(row, COL_NOTES_EN)
        entries.append((en, target, notes[:NOTES_MAX]))

    lines = [
        f'# Glossary: {locale}',
        '',
        f'> {len(entries)} entries — synced from Google Sheets by scripts/sync-glossaries.py.',
        f'> Source of truth is `{locale}.csv`; edit the Sheet, not this file.',
        '',
        f'| English | {locale} | Notes |',
        '|---|---|---|',
    ]
    lines += [f'| {en} | {target} | {notes} |' for en, target, notes in entries]

    with open(os.path.join(OUTDIR, f'{locale}.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    return len(entries)


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    
    print("Refreshing access token...", flush=True)
    try:
        access_token = get_access_token()
    except Exception as e:
        print(f"❌ Token refresh failed: {e}")
        return 1
    
    results = {}
    for locale, sheet_id in GLOSSARIES.items():
        print(f"Syncing {locale}...", flush=True)
        try:
            rows = fetch_sheet(access_token, sheet_id)
            
            outpath = os.path.join(OUTDIR, f"{locale}.csv")
            with open(outpath, 'w', newline='', encoding='utf-8') as f:
                writer = csv.writer(f)
                writer.writerows(rows)
            
            data_rows = [r for r in rows[1:] if len(r) >= 2 and r[0].strip() and r[1].strip()]
            print(f"  ✅ {len(rows)} rows ({len(data_rows)} glossary entries)")
            results[locale] = 'ok'

            # Best-effort: a Markdown failure must not fail a locale whose CSV is already written.
            try:
                print(f"  ✅ {write_markdown(locale, rows)} entries → {locale}.md")
            except Exception as e:
                print(f"  ⚠️  {locale}.md not regenerated ({e}) — CSV is fine, .md may be stale")
        except Exception as e:
            print(f"  ❌ {e}")
            results[locale] = f'error: {e}'
    
    # Write sync metadata
    meta = {
        'last_sync': time.strftime('%Y-%m-%dT%H:%M:%S%z'),
        'method': 'sheets_api_v4',
        'results': results
    }
    with open(os.path.join(OUTDIR, 'sync-meta.json'), 'w') as f:
        json.dump(meta, f, indent=2)
    
    ok_count = sum(1 for v in results.values() if v == 'ok')
    print(f"\n{'✅' if ok_count == len(GLOSSARIES) else '⚠️'} Synced {ok_count}/{len(GLOSSARIES)} glossaries")
    return 0 if ok_count == len(GLOSSARIES) else 1

if __name__ == '__main__':
    sys.exit(main())
